# Fly.io configuration for FLYCouponGen
# Generated for production deployment

app = "flycoupongen"
primary_region = "fra"  # Frankfurt (closest to Italy)

[build]

[env]
  NODE_ENV = "production"
  PORT = "3000"
  SESSION_SECRET = "your-secret-key-change-in-production"
  DEFAULT_TENANT_SLUG = "default"
  DEFAULT_TENANT_NAME = "Default Tenant"
  ENFORCE_TENANT_PREFIX = "false"
  LOGIN_WINDOW_MS = "600000"
  LOGIN_MAX_ATTEMPTS = "10"
  LOGIN_LOCK_MS = "1800000"
  UPLOAD_MAX_BYTES = "2097152"
  SUBMIT_WINDOW_MS = "600000"
  SUBMIT_MAX_PER_IP = "20"
  SUBMIT_LOCK_MS = "1800000"
  EMAIL_DAILY_WINDOW_MS = "86400000"
  EMAIL_MAX_PER_DAY = "3"
  EMAIL_LOCK_MS = "86400000"
  RECAPTCHA_ENABLED = "false"
  MAIL_PROVIDER = "mailgun"
  MAIL_SUBJECT = "Il tuo coupon"
  MAIL_FROM = "CouponGen <no-reply@send.coupongen.it>"
  DEFAULT_DISCOUNT_PERCENT = "10"

# HTTP service configuration
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/healthz"

# Machine configuration
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

# Persistent volume for SQLite database and uploads
[[mounts]]
  source = "coupongen_data"
  destination = "/app/data"

# Health check configuration
[checks]
  [checks.healthz]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/healthz"

# Process groups
[processes]
  app = "node server.js"

# Redis configuration (using Fly.io Redis)
[[services]]
  protocol = "tcp"
  internal_port = 6379
  
  [[services.ports]]
    port = 6379
    handlers = ["tcp"]
