# Fly.io configuration for FLYCouponGen - STAGING
# Generated for staging deployment

app = "flycoupongen-staging"
primary_region = "fra"  # Frankfurt (closest to Italy)

[build]

[env]
  NODE_ENV = "staging"
  PORT = "3000"
  SESSION_SECRET = "staging-secret-key-change-in-production"
  DEFAULT_TENANT_SLUG = "staging"
  DEFAULT_TENANT_NAME = "Staging Tenant"
  ENFORCE_TENANT_PREFIX = "false"
  LOGIN_WINDOW_MS = "600000"
  LOGIN_MAX_ATTEMPTS = "10"
  LOGIN_LOCK_MS = "1800000"
  UPLOAD_MAX_BYTES = "2097152"
  SUBMIT_WINDOW_MS = "600000"
  SUBMIT_MAX_PER_IP = "20"
  SUBMIT_LOCK_MS = "1800000"
  EMAIL_DAILY_WINDOW_MS = "86400000"
  EMAIL_MAX_PER_DAY = "3"
  EMAIL_LOCK_MS = "86400000"
  RECAPTCHA_ENABLED = "false"
  MAIL_PROVIDER = "mailgun"
  MAIL_SUBJECT = "[STAGING] Il tuo coupon"
  MAIL_FROM = "CouponGen Staging <no-reply@send.coupongen.it>"
  DEFAULT_DISCOUNT_PERCENT = "10"

# HTTP service configuration
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0  # Staging can be stopped when not in use
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/healthz"

# Machine configuration (smaller for staging)
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

# Persistent volume for SQLite database and uploads
[[mounts]]
  source = "coupongen_staging_data"
  destination = "/app/data"

# Health check configuration
[checks]
  [checks.healthz]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/healthz"

# Process groups
[processes]
  app = "node server.js"
